# Client Side

[Intellical]
UpgradeProduct=LightField 6
OEMImagePrefix=LightField
WelcomeTitleHeaderText=LightField License Upgrade
WelcomeHeaderMsg=We will now upgrade your USB key with a license for %UpgradeProduct%.
WelcomePleasePurchaseMsg=
WelcomeNextMsg=If you have your unlocking code, click "next" to proceed.
DownloadingHeader=Downloading
DownloadFailureHeading=Download Failure
DownloadFailureSubHeading=Download did not finish.
DownloadFailureMsg=There was a problem and we could not complete the requested download.
DownloadFailureButtonMsg=What would you like to do?
